"""Criação inicial

Revision ID: 1d4d3304c7c5
Revises: 
Create Date: 2024-01-15 15:52:11.565469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d4d3304c7c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('grade1', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.Column('grade2', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('calculations', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb3_bin', length=100),
               nullable=False)

    op.drop_table('movies')
    # ### end Alembic commands ###
