"""+ coluna image em tabela Movies

Revision ID: 8e3b455f6ddc
Revises: 5c0d836e0c0c
Create Date: 2024-01-18 10:15:00.385402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3b455f6ddc'
down_revision = '5c0d836e0c0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.LargeBinary(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
